name: "Protoc Go Stubs Generation"

on:
  push:
    tags:
      - v**

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        service: ["order", "payment", "shipping"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Configure Git
        run: |
          git config --global user.email "muhamad.salman2001@gmail.com"
          git config --global user.name "MHS-20"
      
      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/run.sh"
          ./run.sh ${{ matrix.service }} $RELEASE_VERSION 